#!/bin/bash
# Profile Switcher - Switch to Corporate Profile
# Auto-generated by profile-switcher plugin

CLAUDE_DIR="$HOME/.claude"
PROFILES_DIR="$CLAUDE_DIR/profiles"
NPMRC="$HOME/.npmrc"
CONFIG_FILE="$PROFILES_DIR/profile-switcher-config.json"

echo "Switching to CORPORATE profile..."
echo ""

# === Load Configuration ===
if [ -f "$CONFIG_FILE" ]; then
    # Read configuration values
    CORPORATE_GATEWAY=$(python3 -c "import json; config=json.load(open('$CONFIG_FILE')); print(config.get('corporateGatewayUrl', ''))" 2>/dev/null || echo "")
    API_KEY_HELPER=$(python3 -c "import json; config=json.load(open('$CONFIG_FILE')); print(config.get('apiKeyHelperPath', ''))" 2>/dev/null || echo "")
    CORPORATE_NPM=$(python3 -c "import json; config=json.load(open('$CONFIG_FILE')); print(config.get('corporateNpmRegistry', ''))" 2>/dev/null || echo "")
    SYNC_SETTINGS=$(python3 -c "import json; config=json.load(open('$CONFIG_FILE')); print(','.join(config.get('syncSettings', ['enabledPlugins', 'mcpServers'])))" 2>/dev/null || echo "enabledPlugins,mcpServers")

    # Read npm commands
    NPM_COMMANDS=$(python3 -c "import json; config=json.load(open('$CONFIG_FILE')); print('\n'.join(config.get('customNpmCommands', {}).get('onSwitchToCorporate', [])))" 2>/dev/null || echo "")
else
    echo "Warning: Configuration file not found at $CONFIG_FILE"
    echo "Run /profile-setup to configure the profile switcher"
    exit 1
fi

# === Claude Configuration ===
echo "[1/3] Backing up current settings..."

# Backup current settings.json to appropriate profile
if [ -f "$CLAUDE_DIR/settings.json" ]; then
    if grep -q "apiKeyHelper" "$CLAUDE_DIR/settings.json" 2>/dev/null; then
        cp "$CLAUDE_DIR/settings.json" "$PROFILES_DIR/corporate-settings.json"
        echo "  - Backed up current settings to corporate profile"
    else
        cp "$CLAUDE_DIR/settings.json" "$PROFILES_DIR/personal-settings.json"
        echo "  - Backed up current settings to personal profile"
    fi
fi

# Backup personal tokens before switching
if [ -n "$(ls -A $CLAUDE_DIR/tokens/ 2>/dev/null)" ]; then
    mkdir -p "$PROFILES_DIR/tokens-personal"
    cp "$CLAUDE_DIR/tokens/"* "$PROFILES_DIR/tokens-personal/" 2>/dev/null
    echo "  - Backed up personal tokens"
fi

echo ""
echo "[2/3] Syncing common settings between profiles..."

# Sync settings using Python
if command -v python3 &> /dev/null; then
    python3 << PYTHON_SCRIPT
import json
import os

profiles_dir = os.path.expanduser("~/.claude/profiles")
personal_file = os.path.join(profiles_dir, "personal-settings.json")
corporate_file = os.path.join(profiles_dir, "corporate-settings.json")
sync_settings = "$SYNC_SETTINGS".split(',')

# Read both files
try:
    with open(personal_file, 'r') as f:
        personal = json.load(f)
except FileNotFoundError:
    personal = {}

try:
    with open(corporate_file, 'r') as f:
        corporate = json.load(f)
except FileNotFoundError:
    corporate = {}

# Sync specified settings
for setting in sync_settings:
    setting = setting.strip()
    if not setting:
        continue

    if setting in ['enabledPlugins', 'mcpServers']:
        # Merge (union) for these settings
        personal_val = personal.get(setting, {})
        corporate_val = corporate.get(setting, {})
        merged = {**personal_val, **corporate_val}
        personal[setting] = merged
        corporate[setting] = merged
        print(f"  - Synced {setting} across both profiles")
    elif setting == 'alwaysThinkingEnabled':
        # Use corporate value as source of truth for this one
        value = corporate.get(setting, personal.get(setting, False))
        personal[setting] = value
        corporate[setting] = value
        print(f"  - Synced {setting} across both profiles")

# Write back
with open(personal_file, 'w') as f:
    json.dump(personal, f, indent=2)
with open(corporate_file, 'w') as f:
    json.dump(corporate, f, indent=2)
PYTHON_SCRIPT
else
    echo "  - Python3 not found, skipping sync"
fi

echo ""
echo "[3/3] Switching Claude authentication..."

cp "$PROFILES_DIR/corporate-settings.json" "$CLAUDE_DIR/settings.json"

# Set up gateway config if specified
if [ -f "$PROFILES_DIR/corporate-gateway-config.json" ]; then
    cp "$PROFILES_DIR/corporate-gateway-config.json" "$CLAUDE_DIR/gateway-helper-config.json"
elif [ -n "$CORPORATE_GATEWAY" ]; then
    # Create gateway config from settings
    cat > "$CLAUDE_DIR/gateway-helper-config.json" << EOF
{
  "gatewayUrl": "$CORPORATE_GATEWAY"
}
EOF
fi

# Restore corporate tokens if they exist
if [ -d "$PROFILES_DIR/tokens-corporate" ] && [ "$(ls -A $PROFILES_DIR/tokens-corporate 2>/dev/null)" ]; then
    cp "$PROFILES_DIR/tokens-corporate/"* "$CLAUDE_DIR/tokens/" 2>/dev/null
    echo "  - Restored corporate tokens"
else
    echo "  - No corporate tokens to restore (may need to re-authenticate)"
fi

echo "  - Claude: Corporate gateway authentication"
echo ""

# === NPM Configuration ===
echo "[4/4] Switching npm registry..."

# Backup current .npmrc
if [ -f "$NPMRC" ]; then
    mkdir -p "$PROFILES_DIR"
    cp "$NPMRC" "$PROFILES_DIR/npmrc-backup-personal" 2>/dev/null
fi

# Run custom npm commands if provided, otherwise use defaults
if [ -n "$NPM_COMMANDS" ]; then
    echo "$NPM_COMMANDS" | while IFS= read -r cmd; do
        [ -n "$cmd" ] && eval "$cmd" 2>/dev/null
    done
    echo "  - Applied custom npm configuration"
elif [ -n "$CORPORATE_NPM" ]; then
    npm config set registry "$CORPORATE_NPM" 2>/dev/null
    echo "  - NPM: Corporate registry"
else
    echo "  - NPM: No changes made"
fi

echo ""

# === Summary ===
echo "=========================================="
echo "CORPORATE Profile Active"
echo "=========================================="
echo ""
echo "Claude API:"
if [ -n "$CORPORATE_GATEWAY" ]; then
    echo "  - Gateway: $CORPORATE_GATEWAY"
else
    echo "  - Gateway: Configured via gateway-helper-config.json"
fi
echo "  - Auth: Corporate SSO"
echo "  - Billing: Corporate account"
echo ""
echo "NPM Registry:"
echo "  - Registry: $(npm config get registry 2>/dev/null || echo 'default')"
echo ""
echo "Next: Run 'claude' to start"
